name: fast_snackbar
description: A package fast simple Snackabar
version: 0.0.1
repository: https://github.com/Tomjerry12345/firebase_utilitas
license: MIT

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
